"""Add bayesaverage and is_expansion to BoardGame schema

Revision ID: bb3e07fefc19
Revises: 523b31cc433b
Create Date: 2025-02-10 18:47:37.469257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3e07fefc19'
down_revision = '523b31cc433b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bayesaverage', sa.Float(), nullable=False, server_default="0.0"))
        batch_op.add_column(sa.Column('is_expansion', sa.Boolean(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_game', schema=None) as batch_op:
        batch_op.drop_column('is_expansion')
        batch_op.drop_column('bayesaverage')

    # ### end Alembic commands ###
