"""Remove rank column from board_game

Revision ID: de1ce90f91dc
Revises: bb3e07fefc19
Create Date: 2025-02-10 19:50:04.475201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1ce90f91dc'
down_revision = 'bb3e07fefc19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_game', schema=None) as batch_op:
        batch_op.drop_column('rank')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('board_game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
